name: Build and deploy .NET app to Azure Web App - AzureSchoolProject

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Publish .NET project
      run: dotnet publish ./GameStore.csproj -c Release -o ./bin/Release/net8.0/publish --self-contained

    - name: Zip published output
      run: |
        cd ./bin/Release/net8.0/publish
        zip -r ../../../../publish.zip .

    - name: Install Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    - name: Azure CLI login
      run: |
        az login --service-principal \
          --username ${{ secrets.AZURE_CLIENT_ID }} \
          --password ${{ secrets.AZURE_CLIENT_SECRET }} \
          --tenant ${{ secrets.AZURE_TENANT_ID }}

    - name: Deploy to Azure Web App using OneDeploy
      run: |
        az webapp deployment source config-zip \
           --resource-group webapp-rg-dev \
           --name AzureSchoolProject \
           --src publish.zip \
           --timeout 300 || echo "Deployment command exited with error but continuing..."

    - name: Clean up
      run: rm publish.zip