# name: Build and deploy .NET app to Azure Web App - AzureSchoolProject

# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout repository
#       uses: actions/checkout@v4

#     - name: Setup .NET Core SDK
#       uses: actions/setup-dotnet@v3
#       with:
#         dotnet-version: '8.0.x' # or '6.0.x' depending on your project

#     - name: Publish .NET project
#       run: dotnet publish -c Release -o ./publish

#     - name: Deploy to Azure Web App
#       uses: azure/webapps-deploy@v2
#       with:
#         app-name: 'AzureSchoolProject' # Replace with your actual App Service name
#         publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
#         package: ./publish

name: Build and deploy .NET app to Azure Web App - AzureSchoolProject

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Publish .NET project
      run: dotnet publish ./GameStore.csproj -c Release -o ./publish

    - name: List contents of publish folder (for debugging)
      run: ls -R ./publish

    - name: Zip publish folder for Azure
      run: zip -r publish.zip ./publish

    - name: Wait for app service to be ready
      run: sleep 15

    - name: Deploy to Azure Web App
      id: deploy-step
      uses: azure/webapps-deploy@v3
      continue-on-error: true
      with:
        app-name: 'AzureSchoolProject'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
        package: publish.zip

    - name: Retry Deployment (if failed)
      if: steps.deploy-step.outcome == 'failure'
      run: |
        echo "Retrying deployment with Azure CLI..."
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
        az webapp deployment source config-zip \
          --resource-group webapp-rg-dev \
          --name AzureSchoolProject \
          --src publish.zip
